name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          # If you have build steps, include them here. For example:
          # npm install
          # npm run build

      - name: Copy files to root
        run: |
          mkdir -p public
          cp -r server/public/* public/

      
